# Start with the Keycloak image
FROM quay.io/keycloak/keycloak:26.2.5

# Change to the root user to perform privileged operations
USER root

# Copy the setup script into the image
COPY adorsys-keycloak-setup.sh /adorsys-keycloak-setup.sh

# Make the script executable during the image build process
RUN chmod +x /adorsys-keycloak-setup.sh

# Set the new entrypoint to run the script and then wait.
# This keeps the container alive so other services can depend on it.
ENTRYPOINT ["/bin/bash", "-c", "/adorsys-keycloak-setup.sh && tail -f /dev/null"]
