LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule auth_openidc_module modules/mod_auth_openidc.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so

ServerName localhost

User daemon
Group daemon

Listen 80

ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 common

<VirtualHost *:80>
    ProxyPreserveHost On

    ProxyPass / https://localhost/fineract-provider/
    ProxyPassReverse / https://localhost/fineract-provider/

    OIDCCryptoPassphrase asdflksajdfslkajdflsakidf
    OIDCProviderMetadataURL http://172.17.0.1:9000/realms/fineract/.well-known/openid-configuration
    OIDCClientID web-client
    OIDCClientSecret **********
    OIDCRedirectURI http://localhost/callback
    
    <Location />
        AuthType openid-connect
        Require valid-user
    </Location>

</VirtualHost>
