twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.sender.number=${TWILIO_SENDER_NUMBER}
fineract.api.url=${FINERACT_API_URL}
fineract.api.user=${FINERACT_API_USER}
fineract.api.password=${FINERACT_API_PASSWORD}
