apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fineract-helm-chart.fullname" . }}-db-secret
  labels:
    {{- include "fineract-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mariadb.auth.username | b64enc | quote }}
  password: {{ .Values.mariadb.auth.password | b64enc | quote }}
