twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID:}
  auth:
    token: ${TWILIO_AUTH_TOKEN:}
  sender:
    number: ${TWILIO_SENDER_NUMBER:}
fineract:
  api:
    url: ${FINERACT_API_URL:https://fineract:8443/fineract-provider/api/v1}
    user: ${FINERACT_API_USER:mifos}
    password: ${FINERACT_API_PASSWORD:password}
    tenant: ${FINERACT_API_TENANT:default}
  auth:
    type: ${FINERACT_AUTH_TYPE:basic}
keycloak:
  url: ${KEYCLOAK_URL:http://localhost:9000/realms/fineract/protocol/openid-connect/token}
  grant-type: ${KEYCLOAK_GRANT_TYPE:password}
  client-id: ${KEYCLOAK_CLIENT_ID:setup-app-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:**********}
